# Generated by Django 5.1.5 on 2025-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('photo', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('address1', models.TextField()),
                ('state', models.CharField(choices=[('RJ', 'Rajasthan'), ('GJ', 'Gujarat'), ('PB', 'Punjab')], max_length=10)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
