# Generated by Django 5.1.5 on 2025-05-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('relation', models.TextField()),
                ('address', models.TextField()),
                ('address1', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('RJ', 'Rajasthan'), ('GJ', 'Gujarat'), ('PB', 'Punjab')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('reported_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainees', to='front.person')),
            ],
        ),
    ]
