# Generated by Django 5.1.5 on 2025-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_foundperson_claimrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundperson',
            name='location_found',
        ),
        migrations.AddField(
            model_name='foundperson',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='state',
            field=models.CharField(blank=True, choices=[('RJ', 'Rajasthan'), ('GJ', 'Gujarat'), ('PB', 'Punjab')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='photo',
            field=models.ImageField(default='abc.jpg', upload_to='found_photos/'),
            preserve_default=False,
        ),
    ]
