# Generated by Django 5.1.5 on 2025-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_remove_foundperson_location_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='contact',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
