# Generated by Django 5.1.5 on 2025-06-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_foundperson_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='matched_found_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.foundperson'),
        ),
    ]
