# Generated by Django 5.1.5 on 2025-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_complainee_rep_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainee',
            name='notified_about_match',
            field=models.BooleanField(default=False),
        ),
    ]
