# Generated by Django 5.1.5 on 2025-06-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_complainee_notified_about_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('aadhaar_photo', models.ImageField(upload_to='aadhaar_photos/')),
                ('selfie_photo', models.ImageField(upload_to='selfie_photos/')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
