services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    branch: master                # Or change to your branch name
    region: oregon              # Or choose closest region to you
    dockerfilePath: ./Dockerfile
             

